# Generated by Django 5.1.5 on 2025-02-02 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chat',
            table='chatbot_chat',
        ),
        migrations.AlterModelTable(
            name='module',
            table='chatbot_module',
        ),
    ]
