# Generated by Django 5.1.5 on 2025-02-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_chat_table_alter_module_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='question',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='module',
            name='module_title',
            field=models.TextField(),
        ),
    ]
